# Generated by Django 3.2.4 on 2021-07-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210702_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hints',
        ),
    ]
