# Generated by Django 3.2.4 on 2021-07-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_hints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='published',
        ),
    ]
